[package]
name = "polling_vs_mio"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
divan = "0.1.14"
mio = { version = "1.0.1", features = ["os-poll", "net"] }
polling = "3.7.2"

[[bench]]
name = "compare"
harness = false


[profile.bench]
lto = 'fat'

[dependencies]
libc = "0.2.155"
